### ISSUE TITLE
Integrate Sidenav Search

### ISSUE THREAD

**Issue by unitedempire** [Autodesk/orion-ui#244]
As an app developer
I can enable searching my app's sidebar content
so my users can find the modules they are looking for

```jsx
<SideNav>
  <Search placeholder="Search for modules" />
  <SectionList>
    <Section>
      <Group>
        <Module title="Schedule">
          <Submodule title="Master Schedule" />
          <Submodule title="Production Plan" />
        </Module>
      </Group>
    </Section>
  </SectionList>
</SideNav>
```

```js
Search.propTypes = {
  query: PropTypes.string,
  placeholder: PropTypes.string,
  onInput: PropTypes.func,
  onClearIconClick: PropTypes.func,
}
```

---

### Developer notes
- Typing into the search field filters modules and submodules by their title.
- Clicking the clear icon should clear the input and show all modules
- Props should override any internal state
- Search component is optional within SideNav
- Client developer doesn't need to wire anything up for search to work.
---

**Acceptance TODO**
- [x] Add PropTypes
- [x] Add docgenInfo
- [ ] Add unit test coverage
- [x] Add to playground
- [ ] Add to storybook
  - [ ] With code sample
  - [ ] With props table
- [ ] Canary build on NPM
- [ ] Has PO sign off

**Developer TODO**
- [x] integrate collapse into section
- [ ] add tests for submodule and collapse
- [x] and add functionality for search clear button

**Comment by aneyzberg** [comment]
completed by #267 
![side-nav-search-1](https://user-images.githubusercontent.com/5723109/27499595-6f631130-5819-11e7-9f7a-d7c6d0116d17.gif)

**Comment by aneyzberg** [comment]
Here is the canary build - 1.0.3-alpha.c6c369d5

It is also integrated into BIM
