### ISSUE TITLE
Project And Account Switcher doesn't behave according to design when there is only one account and/or project

### ISSUE THREAD

**Issue by unitedempire** [Autodesk/orion-ui#248]
See design here: https://wiki.autodesk.com/download/attachments/315334705/Project%20and%20Account%20Switcher%20-%20Placement.png?version=3&modificationDate=1495747487000&api=v2

**Comment by unitedempire** [comment]
Blocks #215

**Comment by aneyzberg** [comment]
this is finished per PR - https://github.com/Autodesk/orion-ui/pull/249

The canary build is - 1.0.3-alpha.90395624

**Comment by aneyzberg** [comment]
completes https://github.com/Autodesk/orion-ui/issues/248

**Comment by unitedempire** [comment]
<img width="240" alt="sc 2017-06-15 at 10 30 10 am" src="https://user-images.githubusercontent.com/28816911/27186369-22a0e37c-51b6-11e7-8480-ee948dfc46a1.png">

@aneyzberg The implementation still doesn't adhere to the design. Namely, when there is only one project, it shouldn't have a project account switcher.

**Comment by unitedempire** [comment]
Will be addressed by #260
