### ISSUE TITLE
Orion Storybook is broken

### ISSUE THREAD

**Issue by unitedempire** [Autodesk/orion-ui#252]
```
As a developer
I want to see interact and view components in Storybook
So that I can understand how it works and how it is implemented
```

Please take a look at: https://cdn.web-platform.io/orion-ui/orion/snapshot-master/react-hig/index.html

**Comment by shannonwells** [comment]
Storybook is working again except for Shortcuts.

**Comment by Daniel3356** [comment]
URL is not working Thanks for Updating the URL
