### ISSUE TITLE
ProjectAccountSwitcher manages active account and project

### ISSUE THREAD

**Issue by nfiniteset** [Autodesk/orion-ui#260]
As an app developer
use the ProjectAccountSwitcher without configuration
so I can focus on higher-level concerns

### Typical usage 
```jsx
<TopNav>
  <ProjectAccountSwitcher
    onProjectChange={this.setActiveProject}
    onAccountChange={this.setActiveAccount}
  >
    {this.state.accounts.map(account => {
      <Account {...account}/>
    })}
    {this.state.projects.map(project => {
      <Project {...project}/>
    })}
  </ProjectAccountSwitcher>
</TopNav>
```

### Complete props
```js
ProjectAccountSwitcher.propTypes = {
  open: PropTypes.bool,
  onProjectChange: PropTypes.func,
  onAccountChange: PropTypes.func,
  children: HIGChildValidator([AccountComponent, ProjectComponent])
}
```

---

### Developer notes
- [x] ProjectAccountSwitcher opens and closes the flyout without client-app involvement
- [x] ProjectAccountSwitcher manages the active project and account
- [x] ProjectAccountSwitcher has an `onProjectChange` event
- [x] ProjectAccountSwitcher has an `onAccountChange` event
- [x] Keep PropTypes and docgeninfo synchronized.
- [x] Props override any internal state
- [x] If there is only one project, account, or one of each, do not show carat, and do not open flyout
---

**Acceptance TODO**
- [x] Add PropTypes
- [x] Add docgenInfo
- [x] Add unit test coverage
- [x] Add to playground
- [x] Add to storybook
  - [x] With code sample
  - [x] With props table
- [x] Canary build on NPM
- [ ] Has PO sign off

**Comment by nfiniteset** [comment]
@unitedempire This is up for QA on `@orion-ui/react-hig@1.0.3-alpha.4f041340`

**Comment by aneyzberg** [comment]
completed by #269
