### ISSUE TITLE
Tabs manages active tab

### ISSUE THREAD

**Issue by nfiniteset** [Autodesk/orion-ui#262]
As an app developer
I can use Tabs without managing the active tab
so I can focus on higher-level concerns

### Typical usage 
```jsx
<Tabs onTabChange={this.setActiveTab}>
  <Tab label="Alpha" />
  <Tab label="Beta" />
</Tabs>
```

### Complete props
```js
Tabs.propTypes = {
  onTabChange: PropTypes.func,
  children: HIGChildValidator([TabComponent]),
};

Tab.propTypes = {
  active: PropTypes.bool,
  label: PropTypes.string,
};
```

---

### Developer notes
- Tabs tracks active Tab without client app involvement
- Props override any internal state
---

**Acceptance TODO**
- [x] Add PropTypes
- [x] Add docgenInfo
- [x] Add unit test coverage
- [x] Add to playground
- [x] Add to storybook
  - [x] With code sample
  - [x] With props table
- [x] Canary build on NPM
- [ ] Has PO sign off

**Comment by aneyzberg** [comment]
completed by #271 
here is the canary build - 1.0.3-alpha.bf00eb54
