### ISSUE TITLE
GlobalNav manages sidebar open/close

### ISSUE THREAD

**Issue by nfiniteset** [Autodesk/orion-ui#263]
As an app developer
I can use SideNav without managing the open/close state
so I can focus on higher-level concerns

### Typical usage 
```jsx
<GlobalNav>
  <SideNav />
</GlobalNav>
```

### Complete props
```js
GlobalNavComponent.propTypes = {
  sideNavOpen: PropTypes.bool,
  children: HIGChildValidator([
    SideNavComponent,
    TopNavComponent,
    SubNavComponent,
    Slot
  ])
};
```

---

### Developer notes
- GlobalNav opens/closes sidenav without client-app involvement
- Props override any internal state
---

**Acceptance TODO**
- [x] Add PropTypes
- [x] Add docgenInfo
- [x] Add unit test coverage
- [x] Add to playground
- [x] Add to storybook
  - [x] With code sample
  - [x] With props table
- [x] Canary build on NPM
- [ ] Has PO sign off

**Comment by aneyzberg** [comment]
completed by #271 
canary build 1.0.3-alpha.bf00eb54
