### ISSUE TITLE
react-hig TextField onChange is not working as Expected. It Works like blur event

### ISSUE THREAD

**Issue by bankimatglobant** [Autodesk/orion-ui#315]
I am using onChange handler on TextField Component in react-hig but it is not working as expected. It is working like blur event. onChange handler called only on focus change same as onBlur. I want to listen to event on each character change
 
## Expected Behavior
same as above

## Current Behavior
same as above

## How do we reproduce the issue?

1)  Add TextField
2) Pass method for onChange props
3) Try to type in text field
4) passed function should call on each character change.

## What browsers are affected?
I have tried in Google Chrome
All browsers? Some specific browser? What device type?

## Which Orion version is affected?
I am using 1.0.3-alpha.e6196f19 version.

Is this a new issue? Or was it always broken? Paste your Orion version. You can find it in the browser dev tools.

**Comment by camwest** [comment]
Try using onInput instead of onChange. Also FYI this project is being migrated here: https://github.com/Autodesk/hig/tree/master/src/implementations/react

cc @recyclerobot

**Comment by bankimatglobant** [comment]
@camwest Thank you for the quick response. I will raise the issue there if I will find any.
